services:
  - type: web
    name: lipbuddy
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg libsm6 libxext6 libglib2.0-0
      pip install -r requirements.txt
    startCommand: streamlit run streamlitapp.py --server.port $PORT --server.address 0.0.0.0
